START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828065853_AddSandboxPaymentEvents') THEN
    DROP INDEX marketplace."IX_PaymentRecords_OrderId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828065853_AddSandboxPaymentEvents') THEN
    ALTER TABLE marketplace."PaymentRecords" ADD "PaymentKey" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828065853_AddSandboxPaymentEvents') THEN
    CREATE TABLE marketplace."PaymentProviderEvents" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PaymentRecordId" uuid NOT NULL,
        "Provider" character varying(80) NOT NULL,
        "EventId" character varying(160) NOT NULL,
        "EventType" character varying(40) NOT NULL,
        "ReceivedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_PaymentProviderEvents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PaymentProviderEvents_PaymentRecords_PaymentRecordId" FOREIGN KEY ("PaymentRecordId") REFERENCES marketplace."PaymentRecords" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828065853_AddSandboxPaymentEvents') THEN
    CREATE UNIQUE INDEX "IX_PaymentRecords_OrderId_PaymentKey" ON marketplace."PaymentRecords" ("OrderId", "PaymentKey") WHERE "PaymentKey" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828065853_AddSandboxPaymentEvents') THEN
    CREATE INDEX "IX_PaymentProviderEvents_PaymentRecordId" ON marketplace."PaymentProviderEvents" ("PaymentRecordId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828065853_AddSandboxPaymentEvents') THEN
    CREATE UNIQUE INDEX "IX_PaymentProviderEvents_Provider_EventId" ON marketplace."PaymentProviderEvents" ("Provider", "EventId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828065853_AddSandboxPaymentEvents') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260828065853_AddSandboxPaymentEvents', '10.0.11');
    END IF;
END $EF$;
COMMIT;

