CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'marketplace') THEN
            CREATE SCHEMA marketplace;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'audit') THEN
            CREATE SCHEMA audit;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'identity') THEN
            CREATE SCHEMA identity;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."Categories" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "ParentCategoryId" uuid,
        "Name" character varying(120) NOT NULL,
        "Slug" character varying(140) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Categories_Categories_ParentCategoryId" FOREIGN KEY ("ParentCategoryId") REFERENCES marketplace."Categories" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE identity."Roles" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE identity."Users" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "DisplayName" character varying(160) NOT NULL,
        "Status" character varying(32) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE identity."RoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES identity."Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."Addresses" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid NOT NULL,
        "Type" character varying(24) NOT NULL,
        "RecipientName" character varying(160) NOT NULL,
        "Line1" character varying(200) NOT NULL,
        "Line2" character varying(200),
        "City" character varying(100) NOT NULL,
        "Province" character varying(100) NOT NULL,
        "PostalCode" character varying(20) NOT NULL,
        "CountryCode" character(2) NOT NULL,
        "IsDefault" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Addresses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE audit."AuditEntries" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid,
        "EntityType" character varying(120) NOT NULL,
        "EntityId" character varying(120) NOT NULL,
        "Action" character varying(80) NOT NULL,
        "ChangesJson" jsonb,
        "CorrelationId" character varying(120),
        "OccurredAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_AuditEntries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AuditEntries_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."Carts" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "CustomerId" uuid NOT NULL,
        "Status" character varying(32) NOT NULL,
        "ExpiresAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Carts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Carts_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES identity."Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."CustomerProfiles" (
        "UserId" uuid NOT NULL,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "MobileNumber" character varying(32),
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_CustomerProfiles" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_CustomerProfiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."Orders" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "OrderNumber" character varying(40) NOT NULL,
        "CustomerId" uuid NOT NULL,
        "Status" character varying(40) NOT NULL,
        "Subtotal" numeric(18,2) NOT NULL,
        "DiscountTotal" numeric(18,2) NOT NULL,
        "DeliveryTotal" numeric(18,2) NOT NULL,
        "GrandTotal" numeric(18,2) NOT NULL,
        "Currency" character(3) NOT NULL,
        "PlacedAt" timestamp with time zone,
        "PaidAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Orders_Totals" CHECK ("Subtotal" >= 0 AND "DiscountTotal" >= 0 AND "DeliveryTotal" >= 0 AND "GrandTotal" >= 0),
        CONSTRAINT "FK_Orders_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES identity."Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."SellerProfiles" (
        "UserId" uuid NOT NULL,
        "TradingName" character varying(180) NOT NULL,
        "RegistrationNumber" character varying(80),
        "TaxNumber" character varying(80),
        "Status" character varying(32) NOT NULL,
        "CommissionRate" numeric(5,4) NOT NULL DEFAULT 0.1,
        "ApprovedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_SellerProfiles" PRIMARY KEY ("UserId"),
        CONSTRAINT "CK_SellerProfiles_CommissionRate" CHECK ("CommissionRate" >= 0 AND "CommissionRate" <= 1),
        CONSTRAINT "FK_SellerProfiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE identity."UserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE identity."UserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE identity."UserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES identity."Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE identity."UserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."OrderAddresses" (
        "OrderId" uuid NOT NULL,
        "RecipientName" character varying(160) NOT NULL,
        "Line1" character varying(200) NOT NULL,
        "Line2" character varying(200),
        "City" character varying(100) NOT NULL,
        "Province" character varying(100) NOT NULL,
        "PostalCode" character varying(20) NOT NULL,
        "CountryCode" character(2) NOT NULL,
        CONSTRAINT "PK_OrderAddresses" PRIMARY KEY ("OrderId"),
        CONSTRAINT "FK_OrderAddresses_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES marketplace."Orders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."PaymentRecords" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "OrderId" uuid NOT NULL,
        "Provider" character varying(80) NOT NULL,
        "ProviderReference" character varying(160),
        "PaymentMethodType" character varying(80) NOT NULL,
        "Status" character varying(40) NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Currency" character(3) NOT NULL,
        "FailureReason" character varying(500),
        "PaidAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_PaymentRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_PaymentRecords_Amount" CHECK ("Amount" >= 0),
        CONSTRAINT "FK_PaymentRecords_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES marketplace."Orders" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."Promotions" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "SellerId" uuid,
        "Code" character varying(60) NOT NULL,
        "Name" character varying(180) NOT NULL,
        "Type" character varying(32) NOT NULL,
        "Status" character varying(32) NOT NULL,
        "Value" numeric(18,2) NOT NULL,
        "MinimumOrderAmount" numeric(18,2),
        "UsageLimit" integer,
        "StartsAt" timestamp with time zone NOT NULL,
        "EndsAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Promotions" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Promotions_Dates" CHECK ("EndsAt" > "StartsAt"),
        CONSTRAINT "CK_Promotions_Value" CHECK ("Value" > 0),
        CONSTRAINT "FK_Promotions_SellerProfiles_SellerId" FOREIGN KEY ("SellerId") REFERENCES marketplace."SellerProfiles" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."SellerPayouts" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "SellerId" uuid NOT NULL,
        "PeriodStart" date NOT NULL,
        "PeriodEnd" date NOT NULL,
        "GrossSales" numeric(18,2) NOT NULL,
        "PlatformFees" numeric(18,2) NOT NULL,
        "Refunds" numeric(18,2) NOT NULL,
        "NetAmount" numeric(18,2) NOT NULL,
        "Status" character varying(32) NOT NULL,
        "ExternalReference" character varying(160),
        "PaidAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_SellerPayouts" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_SellerPayouts_Amounts" CHECK ("GrossSales" >= 0 AND "PlatformFees" >= 0 AND "Refunds" >= 0 AND "NetAmount" >= 0),
        CONSTRAINT "CK_SellerPayouts_Period" CHECK ("PeriodEnd" >= "PeriodStart"),
        CONSTRAINT "FK_SellerPayouts_SellerProfiles_SellerId" FOREIGN KEY ("SellerId") REFERENCES marketplace."SellerProfiles" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."Stores" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "SellerId" uuid NOT NULL,
        "Name" character varying(180) NOT NULL,
        "Slug" character varying(180) NOT NULL,
        "Description" character varying(2000),
        "SupportEmail" character varying(256),
        "Status" character varying(32) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Stores" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Stores_SellerProfiles_SellerId" FOREIGN KEY ("SellerId") REFERENCES marketplace."SellerProfiles" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."Products" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "StoreId" uuid NOT NULL,
        "Sku" character varying(80) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Slug" character varying(220) NOT NULL,
        "Description" character varying(4000),
        "Price" numeric(18,2) NOT NULL,
        "Currency" character(3) NOT NULL,
        "Status" character varying(32) NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Products_Price" CHECK ("Price" >= 0),
        CONSTRAINT "FK_Products_Stores_StoreId" FOREIGN KEY ("StoreId") REFERENCES marketplace."Stores" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."SellerOrders" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "OrderId" uuid NOT NULL,
        "SellerId" uuid NOT NULL,
        "StoreId" uuid NOT NULL,
        "Status" character varying(40) NOT NULL,
        "Subtotal" numeric(18,2) NOT NULL,
        "DiscountTotal" numeric(18,2) NOT NULL,
        "DeliveryTotal" numeric(18,2) NOT NULL,
        "CommissionAmount" numeric(18,2) NOT NULL,
        "SellerNetAmount" numeric(18,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_SellerOrders" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_SellerOrders_Totals" CHECK ("Subtotal" >= 0 AND "DiscountTotal" >= 0 AND "DeliveryTotal" >= 0 AND "CommissionAmount" >= 0 AND "SellerNetAmount" >= 0),
        CONSTRAINT "FK_SellerOrders_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES marketplace."Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SellerOrders_SellerProfiles_SellerId" FOREIGN KEY ("SellerId") REFERENCES marketplace."SellerProfiles" ("UserId") ON DELETE RESTRICT,
        CONSTRAINT "FK_SellerOrders_Stores_StoreId" FOREIGN KEY ("StoreId") REFERENCES marketplace."Stores" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."CartItems" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "CartId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "Quantity" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_CartItems_Quantity" CHECK ("Quantity" > 0),
        CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES marketplace."Carts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CartItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES marketplace."Products" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."InventoryItems" (
        "ProductId" uuid NOT NULL,
        "OnHandQuantity" integer NOT NULL,
        "ReservedQuantity" integer NOT NULL,
        "ReorderLevel" integer NOT NULL,
        "Version" bigint NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_InventoryItems" PRIMARY KEY ("ProductId"),
        CONSTRAINT "CK_InventoryItems_Quantities" CHECK ("OnHandQuantity" >= 0 AND "ReservedQuantity" >= 0 AND "ReservedQuantity" <= "OnHandQuantity" AND "ReorderLevel" >= 0),
        CONSTRAINT "FK_InventoryItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES marketplace."Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."ProductCategories" (
        "ProductId" uuid NOT NULL,
        "CategoryId" uuid NOT NULL,
        CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("ProductId", "CategoryId"),
        CONSTRAINT "FK_ProductCategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES marketplace."Categories" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ProductCategories_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES marketplace."Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."ProductImages" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "ProductId" uuid NOT NULL,
        "StorageKey" character varying(500) NOT NULL,
        "PublicUrl" character varying(1000) NOT NULL,
        "AltText" character varying(300) NOT NULL,
        "SortOrder" integer NOT NULL,
        "IsPrimary" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_ProductImages" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_ProductImages_SortOrder" CHECK ("SortOrder" >= 0),
        CONSTRAINT "FK_ProductImages_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES marketplace."Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."PromotionProducts" (
        "PromotionId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        CONSTRAINT "PK_PromotionProducts" PRIMARY KEY ("PromotionId", "ProductId"),
        CONSTRAINT "FK_PromotionProducts_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES marketplace."Products" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_PromotionProducts_Promotions_PromotionId" FOREIGN KEY ("PromotionId") REFERENCES marketplace."Promotions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."OrderItems" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "SellerOrderId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "SkuSnapshot" character varying(80) NOT NULL,
        "ProductNameSnapshot" character varying(200) NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(18,2) NOT NULL,
        "DiscountAmount" numeric(18,2) NOT NULL,
        "LineTotal" numeric(18,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_OrderItems_Quantity" CHECK ("Quantity" > 0),
        CONSTRAINT "CK_OrderItems_Totals" CHECK ("UnitPrice" >= 0 AND "DiscountAmount" >= 0 AND "LineTotal" >= 0),
        CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES marketplace."Products" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_OrderItems_SellerOrders_SellerOrderId" FOREIGN KEY ("SellerOrderId") REFERENCES marketplace."SellerOrders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."SellerPayoutItems" (
        "SellerPayoutId" uuid NOT NULL,
        "SellerOrderId" uuid NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_SellerPayoutItems" PRIMARY KEY ("SellerPayoutId", "SellerOrderId"),
        CONSTRAINT "CK_SellerPayoutItems_Amount" CHECK ("Amount" >= 0),
        CONSTRAINT "FK_SellerPayoutItems_SellerOrders_SellerOrderId" FOREIGN KEY ("SellerOrderId") REFERENCES marketplace."SellerOrders" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_SellerPayoutItems_SellerPayouts_SellerPayoutId" FOREIGN KEY ("SellerPayoutId") REFERENCES marketplace."SellerPayouts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."Shipments" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "SellerOrderId" uuid NOT NULL,
        "Status" character varying(32) NOT NULL,
        "Carrier" character varying(100),
        "TrackingNumber" character varying(160),
        "DispatchedAt" timestamp with time zone,
        "DeliveredAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Shipments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Shipments_SellerOrders_SellerOrderId" FOREIGN KEY ("SellerOrderId") REFERENCES marketplace."SellerOrders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."InventoryTransactions" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "ProductId" uuid NOT NULL,
        "Type" character varying(32) NOT NULL,
        "QuantityDelta" integer NOT NULL,
        "ReferenceType" character varying(80),
        "ReferenceId" uuid,
        "Reason" character varying(500) NOT NULL,
        "CreatedByUserId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_InventoryTransactions" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_InventoryTransactions_Delta" CHECK ("QuantityDelta" <> 0),
        CONSTRAINT "FK_InventoryTransactions_InventoryItems_ProductId" FOREIGN KEY ("ProductId") REFERENCES marketplace."InventoryItems" ("ProductId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."ReturnRequests" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "OrderItemId" uuid NOT NULL,
        "CustomerId" uuid NOT NULL,
        "Quantity" integer NOT NULL,
        "Reason" character varying(200) NOT NULL,
        "Details" character varying(2000),
        "Status" character varying(32) NOT NULL,
        "RefundAmount" numeric(18,2) NOT NULL,
        "RequestedAt" timestamp with time zone NOT NULL,
        "ResolvedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_ReturnRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_ReturnRequests_Quantity" CHECK ("Quantity" > 0),
        CONSTRAINT "CK_ReturnRequests_RefundAmount" CHECK ("RefundAmount" >= 0),
        CONSTRAINT "FK_ReturnRequests_OrderItems_OrderItemId" FOREIGN KEY ("OrderItemId") REFERENCES marketplace."OrderItems" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ReturnRequests_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES identity."Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."StockReservations" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "OrderItemId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "Quantity" integer NOT NULL,
        "Status" character varying(32) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "ReleasedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_StockReservations" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_StockReservations_Quantity" CHECK ("Quantity" > 0),
        CONSTRAINT "FK_StockReservations_InventoryItems_ProductId" FOREIGN KEY ("ProductId") REFERENCES marketplace."InventoryItems" ("ProductId") ON DELETE RESTRICT,
        CONSTRAINT "FK_StockReservations_OrderItems_OrderItemId" FOREIGN KEY ("OrderItemId") REFERENCES marketplace."OrderItems" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE TABLE marketplace."RefundRecords" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "ReturnRequestId" uuid NOT NULL,
        "PaymentRecordId" uuid,
        "ProviderReference" character varying(160),
        "Status" character varying(32) NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "PaidAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_RefundRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_RefundRecords_Amount" CHECK ("Amount" > 0),
        CONSTRAINT "FK_RefundRecords_PaymentRecords_PaymentRecordId" FOREIGN KEY ("PaymentRecordId") REFERENCES marketplace."PaymentRecords" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RefundRecords_ReturnRequests_ReturnRequestId" FOREIGN KEY ("ReturnRequestId") REFERENCES marketplace."ReturnRequests" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    INSERT INTO identity."Roles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('11111111-1111-1111-1111-111111111111', 'role-customer-v1', 'Customer', 'CUSTOMER');
    INSERT INTO identity."Roles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('22222222-2222-2222-2222-222222222222', 'role-seller-v1', 'Seller', 'SELLER');
    INSERT INTO identity."Roles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('33333333-3333-3333-3333-333333333333', 'role-productadministrator-v1', 'ProductAdministrator', 'PRODUCTADMINISTRATOR');
    INSERT INTO identity."Roles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('44444444-4444-4444-4444-444444444444', 'role-fulfilmentemployee-v1', 'FulfilmentEmployee', 'FULFILMENTEMPLOYEE');
    INSERT INTO identity."Roles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('55555555-5555-5555-5555-555555555555', 'role-businessmanager-v1', 'BusinessManager', 'BUSINESSMANAGER');
    INSERT INTO identity."Roles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('66666666-6666-6666-6666-666666666666', 'role-systemadministrator-v1', 'SystemAdministrator', 'SYSTEMADMINISTRATOR');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_Addresses_UserId_IsDefault" ON marketplace."Addresses" ("UserId", "IsDefault");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_AuditEntries_EntityType_EntityId" ON audit."AuditEntries" ("EntityType", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_AuditEntries_OccurredAt" ON audit."AuditEntries" ("OccurredAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_AuditEntries_UserId" ON audit."AuditEntries" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_CartItems_CartId_ProductId" ON marketplace."CartItems" ("CartId", "ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_CartItems_ProductId" ON marketplace."CartItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_Carts_CustomerId_Status" ON marketplace."Carts" ("CustomerId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_Categories_ParentCategoryId" ON marketplace."Categories" ("ParentCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_Categories_Slug" ON marketplace."Categories" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_InventoryTransactions_ProductId_CreatedAt" ON marketplace."InventoryTransactions" ("ProductId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_OrderItems_ProductId" ON marketplace."OrderItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_OrderItems_SellerOrderId" ON marketplace."OrderItems" ("SellerOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_Orders_CustomerId_CreatedAt" ON marketplace."Orders" ("CustomerId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_Orders_OrderNumber" ON marketplace."Orders" ("OrderNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_PaymentRecords_OrderId" ON marketplace."PaymentRecords" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_PaymentRecords_Provider_ProviderReference" ON marketplace."PaymentRecords" ("Provider", "ProviderReference") WHERE "ProviderReference" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_ProductCategories_CategoryId" ON marketplace."ProductCategories" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_ProductImages_ProductId_SortOrder" ON marketplace."ProductImages" ("ProductId", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_ProductImages_StorageKey" ON marketplace."ProductImages" ("StorageKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_Products_Sku" ON marketplace."Products" ("Sku");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_Products_StoreId_Slug" ON marketplace."Products" ("StoreId", "Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_PromotionProducts_ProductId" ON marketplace."PromotionProducts" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_Promotions_Code" ON marketplace."Promotions" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_Promotions_SellerId" ON marketplace."Promotions" ("SellerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_RefundRecords_PaymentRecordId" ON marketplace."RefundRecords" ("PaymentRecordId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_RefundRecords_ReturnRequestId" ON marketplace."RefundRecords" ("ReturnRequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_ReturnRequests_CustomerId" ON marketplace."ReturnRequests" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_ReturnRequests_OrderItemId_CustomerId_CreatedAt" ON marketplace."ReturnRequests" ("OrderItemId", "CustomerId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_RoleClaims_RoleId" ON identity."RoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON identity."Roles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_SellerOrders_OrderId_StoreId" ON marketplace."SellerOrders" ("OrderId", "StoreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_SellerOrders_SellerId" ON marketplace."SellerOrders" ("SellerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_SellerOrders_StoreId" ON marketplace."SellerOrders" ("StoreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_SellerPayoutItems_SellerOrderId" ON marketplace."SellerPayoutItems" ("SellerOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_SellerPayouts_ExternalReference" ON marketplace."SellerPayouts" ("ExternalReference") WHERE "ExternalReference" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_SellerPayouts_SellerId_PeriodStart_PeriodEnd" ON marketplace."SellerPayouts" ("SellerId", "PeriodStart", "PeriodEnd");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_Shipments_Carrier_TrackingNumber" ON marketplace."Shipments" ("Carrier", "TrackingNumber") WHERE "TrackingNumber" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_Shipments_SellerOrderId" ON marketplace."Shipments" ("SellerOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_StockReservations_OrderItemId" ON marketplace."StockReservations" ("OrderItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_StockReservations_ProductId_Status_ExpiresAt" ON marketplace."StockReservations" ("ProductId", "Status", "ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_Stores_SellerId" ON marketplace."Stores" ("SellerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "IX_Stores_Slug" ON marketplace."Stores" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_UserClaims_UserId" ON identity."UserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_UserLogins_UserId" ON identity."UserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "IX_UserRoles_RoleId" ON identity."UserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE INDEX "EmailIndex" ON identity."Users" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON identity."Users" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827223811_InitialMarketplaceSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260827223811_InitialMarketplaceSchema', '10.0.11');
    END IF;
END $EF$;
COMMIT;
